#!/usr/bin/env python3
"""Download codeparrot/codeparrot-clean via streaming with quality filtering.

Streams the dataset to avoid loading 50GB into memory. Applies quality filters
and writes Parquet shards of 100K rows each.

Filters:
  - Skip autogenerated files (autogenerated == True)
  - Skip low-alpha files (alpha_frac < 0.25)
  - Skip very long files (> 100KB)
  - Skip very short files (< 50 chars)

Usage:
    /usr/bin/python3 scripts/download-codeparrot.py \
        --output /mnt/nvme-raid0/albor-data/codeparrot-clean/ \
        --max-rows 2000000
"""
import argparse
import os
import time

import pyarrow as pa
import pyarrow.parquet as pq
from datasets import load_dataset


def passes_filter(example):
    """Quality filter for Python code files."""
    content = example.get("content", "")
    if not content or len(content) < 50:
        return False
    if len(content) > 100_000:
        return False
    if example.get("autogenerated", False):
        return False
    alpha_frac = example.get("alpha_frac", 1.0)
    if alpha_frac is not None and alpha_frac < 0.25:
        return False
    return True


def main():
    parser = argparse.ArgumentParser(description="Download codeparrot-clean")
    parser.add_argument("--output", required=True, help="Output directory for Parquet shards")
    parser.add_argument("--max-rows", type=int, default=2_000_000,
                        help="Maximum rows to download (default: 2M)")
    parser.add_argument("--shard-size", type=int, default=100_000,
                        help="Rows per Parquet shard (default: 100K)")
    args = parser.parse_args()

    os.makedirs(args.output, exist_ok=True)

    print(f"Streaming codeparrot/codeparrot-clean (max {args.max_rows:,} rows)...")
    ds = load_dataset("codeparrot/codeparrot-clean", split="train", streaming=True)

    shard_idx = 0
    shard_texts = []
    total_kept = 0
    total_seen = 0
    total_tokens_est = 0
    start = time.time()

    for example in ds:
        total_seen += 1

        if not passes_filter(example):
            continue

        content = example["content"]
        shard_texts.append(content)
        total_kept += 1
        total_tokens_est += len(content) // 4  # rough estimate: 4 chars/token

        if len(shard_texts) >= args.shard_size:
            _write_shard(args.output, shard_idx, shard_texts)
            elapsed = time.time() - start
            print(f"  Shard {shard_idx}: {total_kept:,} kept / {total_seen:,} seen "
                  f"({total_kept/total_seen*100:.1f}% pass rate) "
                  f"~{total_tokens_est:,} tokens est. "
                  f"({elapsed:.0f}s)")
            shard_texts = []
            shard_idx += 1

        if total_kept >= args.max_rows:
            break

    # Write remaining
    if shard_texts:
        _write_shard(args.output, shard_idx, shard_texts)
        shard_idx += 1

    elapsed = time.time() - start
    print(f"\nDone: {total_kept:,} files in {shard_idx} shards")
    print(f"  Seen: {total_seen:,} ({total_kept/max(total_seen,1)*100:.1f}% pass rate)")
    print(f"  Estimated tokens: {total_tokens_est:,}")
    print(f"  Time: {elapsed:.0f}s")
    print(f"  Output: {args.output}")


def _write_shard(output_dir, idx, texts):
    """Write a shard of texts to Parquet."""
    table = pa.table({"text": pa.array(texts, type=pa.string())})
    path = os.path.join(output_dir, f"shard-{idx:04d}.parquet")
    pq.write_table(table, path)


if __name__ == "__main__":
    main()
