#!/usr/bin/env python3
"""Filter codeparrot-clean for high-quality Python code.

Downloads codeparrot-clean from HuggingFace, applies quality filters,
writes filtered corpus as Parquet shards ready for pretokenization.

Quality filters (§6.4.2):
  - Syntax validity: ast.parse() must succeed
  - Min length: ≥10 lines, ≥200 chars
  - Max length: ≤10K lines
  - Docstring density: ≥1 docstring per 50 lines
  - Import diversity: ≥2 unique imports
  - No binary/generated markers

Usage:
    # Install deps
    uv pip install datasets pyarrow

    # Run (streams from HuggingFace, ~2h for full corpus)
    python3 scripts/filter_codeparrot.py --output data/filtered/

    # Quick test (first 10K files)
    python3 scripts/filter_codeparrot.py --output data/filtered/ --limit 10000
"""

import argparse
import ast
import os
import re
import sys
import time
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq


def is_valid_python(code: str) -> bool:
    """Check if code parses as valid Python."""
    try:
        ast.parse(code)
        return True
    except (SyntaxError, ValueError, RecursionError):
        return False


def count_docstrings(tree: ast.AST) -> int:
    """Count docstring nodes in AST."""
    count = 0
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Module)):
            if (node.body and isinstance(node.body[0], ast.Expr)
                    and isinstance(node.body[0].value, (ast.Constant, ast.Str))):
                count += 1
    return count


def count_unique_imports(tree: ast.AST) -> int:
    """Count unique imported modules."""
    modules = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                modules.add(alias.name.split('.')[0])
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                modules.add(node.module.split('.')[0])
    return len(modules)


# Patterns that indicate generated/low-quality code
GENERATED_MARKERS = [
    b"# auto-generated",
    b"# generated by",
    b"# do not edit",
    b"# this file is automatically",
    b"# flake8: noqa",
    b"# pylint: skip-file",
    b"# -*- coding:",  # often just encoding headers with no real code
]


def passes_quality_filter(code: str) -> tuple[bool, str]:
    """Apply quality filters. Returns (passed, reject_reason)."""
    # Length filters
    lines = code.split('\n')
    num_lines = len(lines)
    if num_lines < 10:
        return False, "too_short_lines"
    if len(code) < 200:
        return False, "too_short_chars"
    if num_lines > 10000:
        return False, "too_long"

    # Generated code markers
    code_lower = code[:2000].lower().encode('utf-8', errors='ignore')
    for marker in GENERATED_MARKERS:
        if marker in code_lower:
            return False, "generated"

    # Syntax validity (guard against huge files crashing ast.parse)
    if len(code) > 500_000:
        return False, "too_long"
    try:
        tree = ast.parse(code)
    except (SyntaxError, ValueError, RecursionError, MemoryError):
        return False, "syntax_error"

    # Docstring density: at least 1 per 50 lines
    num_docstrings = count_docstrings(tree)
    if num_lines >= 50 and num_docstrings < (num_lines // 50):
        return False, "low_docstring_density"

    # Import diversity: at least 2 unique imports
    num_imports = count_unique_imports(tree)
    if num_imports < 2:
        return False, "low_import_diversity"

    # Ratio of code to comments — reject if >60% comments
    comment_lines = sum(1 for l in lines if l.strip().startswith('#'))
    if num_lines > 20 and comment_lines / num_lines > 0.6:
        return False, "mostly_comments"

    return True, "passed"


def main():
    parser = argparse.ArgumentParser(description="Filter codeparrot-clean")
    parser.add_argument("--output", default="data/filtered/", help="Output directory")
    parser.add_argument("--limit", type=int, default=0, help="Limit number of files (0=all)")
    parser.add_argument("--shard-size", type=int, default=50000, help="Rows per shard")
    args = parser.parse_args()

    try:
        from datasets import load_dataset
    except ImportError:
        print("ERROR: pip install datasets")
        sys.exit(1)

    os.makedirs(args.output, exist_ok=True)
    os.makedirs(os.path.join(args.output, "train"), exist_ok=True)

    print("Loading codeparrot-clean (streaming)...")
    ds = load_dataset("codeparrot/codeparrot-clean", split="train", streaming=True)

    stats = {
        "total": 0,
        "passed": 0,
        "too_short_lines": 0,
        "too_short_chars": 0,
        "too_long": 0,
        "generated": 0,
        "syntax_error": 0,
        "low_docstring_density": 0,
        "low_import_diversity": 0,
        "mostly_comments": 0,
    }

    shard_idx = 0
    buffer = []
    t0 = time.time()

    for i, example in enumerate(ds):
        if args.limit > 0 and i >= args.limit:
            break

        stats["total"] += 1
        code = example.get("content", "")

        passed, reason = passes_quality_filter(code)
        if passed:
            stats["passed"] += 1
            buffer.append(code)
        else:
            stats[reason] = stats.get(reason, 0) + 1

        # Write shard when buffer is full
        if len(buffer) >= args.shard_size:
            shard_path = os.path.join(args.output, "train", f"shard-{shard_idx:04d}.parquet")
            table = pa.table({"content": buffer})
            pq.write_table(table, shard_path)
            print(f"  Wrote shard {shard_idx}: {len(buffer)} files → {shard_path}")
            shard_idx += 1
            buffer = []

        # Progress
        if stats["total"] % 50000 == 0:
            elapsed = time.time() - t0
            rate = stats["total"] / elapsed
            pct = stats["passed"] / stats["total"] * 100
            print(f"  [{stats['total']:>8d}] {stats['passed']:>7d} passed ({pct:.1f}%), "
                  f"{rate:.0f} files/s", flush=True)

    # Write remaining buffer
    if buffer:
        shard_path = os.path.join(args.output, "train", f"shard-{shard_idx:04d}.parquet")
        table = pa.table({"content": buffer})
        pq.write_table(table, shard_path)
        print(f"  Wrote shard {shard_idx}: {len(buffer)} files → {shard_path}")

    elapsed = time.time() - t0
    pct = stats["passed"] / max(1, stats["total"]) * 100

    print(f"\nDone in {elapsed:.0f}s")
    print(f"  Total: {stats['total']:,}")
    print(f"  Passed: {stats['passed']:,} ({pct:.1f}%)")
    print(f"  Rejected breakdown:")
    for reason in ["syntax_error", "too_short_lines", "too_short_chars", "too_long",
                    "generated", "low_docstring_density", "low_import_diversity", "mostly_comments"]:
        count = stats.get(reason, 0)
        if count > 0:
            print(f"    {reason}: {count:,} ({count/stats['total']*100:.1f}%)")


if __name__ == "__main__":
    main()
